sonar.projectKey=VTI_Clothing_Shop_Client
sonar.projectName=VTI Clothing Shop Client
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx

sonar.exclusions=coverage/**,**/coverage/**,dist/**,node_modules/**,public/**,src/i18n/generated/**
sonar.coverage.exclusions=coverage/**,**/coverage/**,src/main.jsx,src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx,src/i18n/generated/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
