sonar.projectKey=VTI_Clothing_Shop_Client
sonar.projectName=VTI Clothing Shop Client
sonar.sourceEncoding=UTF-8

sonar.sources=src
sonar.tests=src
sonar.test.inclusions=src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx

sonar.exclusions=dist/**,coverage/**,node_modules/**
sonar.coverage.exclusions=src/main.jsx,src/**/*.test.js,src/**/*.test.jsx,src/**/*.spec.js,src/**/*.spec.jsx
sonar.javascript.lcov.reportPaths=coverage/lcov.info
