import { createApi } from "@reduxjs/toolkit/query/react";
import { api_routes, SHOP_URL } from "../configs/api.config";
import { createBaseQueryWithDummyFallback } from "./dummyFallback.api";

export const importedProductApi = createApi({
  reducerPath: "importedProductApi",
  baseQuery: createBaseQueryWithDummyFallback("importedProduct", {
    baseUrl: SHOP_URL + api_routes.imported_products,
    prepareHeaders: (headers) => {
      const token = localStorage.getItem("token");
      if (token) headers.set("Authorization", `Bearer ${token}`);
      return headers;
    },
  }),
  tagTypes: ["ImportedProduct"],
  endpoints: (builder) => ({
    getImportedProducts: builder.query({
      query: () => "",
      providesTags: ["ImportedProduct"],
    }),
    getImportedProduct: builder.query({
      query: ({ filter, id }) => `${filter}/${id || 0}`,
      providesTags: (result, error, id) => [{ type: "ImportedProduct", id }],
    }),
    addImportedProduct: builder.mutation({
      query: ({
        product_id,
        color_code,
        color_name,
        size,
        height,
        weight,
        material,
        gender,
        importPrice,
        image_url,
        slider_url_1,
        slider_url_2,
        slider_url_3,
        slider_url_4,
        public_id_url,
        public_id_slider_url_1,
        public_id_slider_url_2,
        public_id_slider_url_3,
        public_id_slider_url_4,
        importNumber,
      }) => ({
        url: "",
        method: "POST",
        body: {
          product_id,
          color_code,
          color_name,
          size,
          height,
          weight,
          material,
          gender,
          importPrice,
          image_url,
          slider_url_1,
          slider_url_2,
          slider_url_3,
          slider_url_4,
          public_id_url,
          public_id_slider_url_1,
          public_id_slider_url_2,
          public_id_slider_url_3,
          public_id_slider_url_4,
          importNumber,
        },
      }),
      invalidatesTags: ["ImportedProduct"],
    }),
    updateImportedProduct: builder.mutation({
      query: ({
        id,
        product_id,
        color_code,
        color_name,
        size,
        height,
        weight,
        material,
        gender,
        importPrice,
        image_url,
        slider_url_1,
        slider_url_2,
        slider_url_3,
        slider_url_4,
        public_id_url,
        public_id_slider_url_1,
        public_id_slider_url_2,
        public_id_slider_url_3,
        public_id_slider_url_4,
        importNumber,
        color_id,
        size_id,
        material_id,
      }) => ({
        url: `${id}`,
        method: "PUT",
        body: {
          product_id,
          color_code,
          color_name,
          size,
          height,
          weight,
          material,
          gender,
          importPrice,
          image_url,
          slider_url_1,
          slider_url_2,
          slider_url_3,
          slider_url_4,
          public_id_url,
          public_id_slider_url_1,
          public_id_slider_url_2,
          public_id_slider_url_3,
          public_id_slider_url_4,
          importNumber,
          color_id,
          size_id,
          material_id,
        },
      }),
      invalidatesTags: ["ImportedProduct"],
    }),
    deleteImportedProduct: builder.mutation({
      query: (id) => ({
        url: `${id}`,
        method: "DELETE",
      }),
      invalidatesTags: ["ImportedProduct"],
    }),
    getColors: builder.query({
      query: () => "/colors",
    }),
    getSizes: builder.query({
      query: () => "/sizes",
    }),
    getMaterials: builder.query({
      query: () => "/materials",
    }),
  }),
});

export const {
  useGetImportedProductsQuery,
  useGetImportedProductQuery,
  useAddImportedProductMutation,
  useDeleteImportedProductMutation,
  useUpdateImportedProductMutation,
  useGetColorsQuery,
  useGetSizesQuery,
  useGetMaterialsQuery,
} = importedProductApi;
